// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0SRmjOWTBwUYtX0zmDZu-hAmFG9azME',
    appId: '1:419448879355:web:09067fd8d3e5778d00585e',
    messagingSenderId: '419448879355',
    projectId: 'smfmobileapp-5b74e',
    authDomain: 'smfmobileapp-5b74e.firebaseapp.com',
    storageBucket: 'smfmobileapp-5b74e.appspot.com',
    measurementId: 'G-CE3VGS25M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7cj4uk1NZgK23Z3jS_gkFCye31RPe9CQ',
    appId: '1:419448879355:android:4cbe3c48fe72c7ba00585e',
    messagingSenderId: '419448879355',
    projectId: 'smfmobileapp-5b74e',
    storageBucket: 'smfmobileapp-5b74e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiU_7LRnlp-GsU_uVls7zLxzuPO1FxlaI',
    appId: '1:419448879355:ios:eabd3166ba18c45000585e',
    messagingSenderId: '419448879355',
    projectId: 'smfmobileapp-5b74e',
    storageBucket: 'smfmobileapp-5b74e.appspot.com',
    iosBundleId: 'com.example.smf',
  );
}
